name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies  
      run: |
        sudo gem install cocoapods
        pod install --verbose
    
    - name: List schemes
      run: xcodebuild -workspace CastBrowser-iOS.xcworkspace -list
    
    - name: Build
      run: xcodebuild -workspace CastBrowser-iOS.xcworkspace -scheme CastBrowser-iOS -destination 'platform=iOS Simulator,name=iPhone 15' build
    
    - name: Run tests
      run: xcodebuild test -workspace CastBrowser-iOS.xcworkspace -scheme CastBrowser-iOS -destination 'platform=iOS Simulator,name=iPhone 15'